### PR TITLE
Addition of the seticon plugin

### PR DESCRIPTION
**Pull request by Kevinxzllz**
This is a plugin that exist on multiple servers, so it seemed like good idea add to your git... I hope you like Philp

[Here a screenshot of as the icon was if you add correctly](http://i.imgur.com/NqYbqDq.png)

### CODE REVIEW

**Comment by TheFenderStory** [comment]
Won't this cause merge conflicts for servers that use github? Also there are some travis errors still

**Comment by Kevinxzllz** [comment]
OK, fix them and upload to a commit

**Comment by TheFenderStory** [comment]
Actually you are gonna need to fix them since you are pull requesting from the master branch of your fork

**Comment by Kevinxzllz** [comment]
Fender fix what my knowledge left me to do... The other errors such as of _"Expected indentation of 1 tab character but found 0"_ not them be corrected...

**Comment by TheFenderStory** [comment]
@Kevinxzllz That just means there is probably a mixture of space and tab characters which you can fix by backspacing the line till there is zero indentation and then using tab to get it to the correct number of indentations.

**Comment by Kevinxzllz** [comment]
Ready @TheFenderStory !!. Fix all the problems, sorry for the delay but these problems had never seen me before.

**Comment by CreaturePhil** [comment]
@Kevinxzllz nice job!

**Comment by Kevinxzllz** [comment]
Thanks Philp, will continue helping on everything i can

**Pull request merged**
