### PR TITLE
bad pull request

### PR DESCRIPTION
**Pull request by Chirou-Cat**

### CODE REVIEW

**Comment by sparkychild** [comment]
https://github.com/Zarel/Pokemon-Showdown/commit/10bb83bf3c877dc44b818e6b4fcebb0b00a69fd9

when will you learn to read

**Comment by Chirou-Cat** [comment]
. . .

**Comment by panpawn** [comment]
I think you mixed up the name of the commit, it should be "why am _i_ so stupid"

**Comment by panpawn** [comment]
still hasn't learned how to read @sparkychild

**Comment by panpawn** [comment]
PS - you didn't change the name of the commit, just the title of the PR

**Pull request closed without merging**
