### PR TITLE
Update README.md (making command simpler for newbies)

### PR DESCRIPTION
**Pull request by Lord-Haji**

### CODE REVIEW

**Comment by TheFenderStory** [comment]
Why not list both? I think ./pokemon-showdown has some support issues on some OS.

**Comment by Lord-Haji** [comment]
ye it fucks with windows
tho perfect with ubuntu and bash on windows.....
also we also use /updateserver which has the same prob as this windows isnt compatible

**Comment by panpawn** [comment]
>bash on windows

**Comment by panpawn** [comment]
Also, people shouldn't really be running a server on Windows

**Comment by Lord-Haji** [comment]
ye exactly right @panpawn if its that then this PR should be merged 2

**Comment by CreaturePhil** [comment]
``node app.js`` is simple enough

**Pull request closed without merging**
