### PR TITLE
Addition of the command roomlist

### PR DESCRIPTION
**Pull request by Kevinxzllz**
Hello again, today I come to enter the command roomlist, that shows a complete list of the rooms available at the server and the amount of users that there are in it, apart from that I also take the opportunity to set the background color of the icons, which used to be white and transparent to better adapt to the server css

I hope you like it, bye :yum:

### CODE REVIEW

**Comment by Kevinxzllz** [comment]
Sorry for the mistake, already or correct

**Comment by TheFenderStory** [comment]
No worries. Good looking code. Just one white space issue nothing major.

**Comment by Kevinxzllz** [comment]
Ready to arrange the small error :yum:

**Comment by Kevinxzllz** [comment]
What happened... something this bad?, have taken too long to respond

**Comment by The-Run** [comment]
I should have never shared that command...

**Pull request closed without merging**
